radar/config/routes.rb
Radar::Engine.routes.draw do
  resources :manages, only:[:index] do 
    collection do
      get :search_form
      get :data_list
      get :object
      get :object_info
      get :object_edit
      get :object_delete
      post :object_update
      post :save_condition
      get :download
    end
  end
end

radar/app/models/radar/application_record.rb
module Radar
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

radar/app/models/radar/business_logic/translation.rb
module Radar
  module BusinessLogic
    
    module Translation
      extend self

      def human_object_names
        # return @object_names if @object_names

        @object_names = {}
        # Rails.application.eager_load! unless Rails.env.production?
        Rails.configuration.eager_load_namespaces.each(&:eager_load!) unless Rails.env.production?

        ActiveRecord::Base.descendants.each do |model|
          next if model.to_s =~ /^ActiveRecord::/
          next if model.to_s =~ /^ActiveStorage::/
          next if model.abstract_class?
          @object_names.merge!({model.model_name.human => model.to_s.gsub('::', '•')})
        end 

        @object_names
      end

      def human_attributes(object:, locale: :zh)
        translates = {}
        object.attributes.each do |key, value|
          translate = human_attribute(object: object, attribute: key, locale: locale)
          next unless translate
          translates.merge!({translate => value})
        end
        
        translates
      end

      def attributes_info(object:, locale: :zh)
        klass = object.class
        info = {}

        object.attributes.each do |key, value|
          translate = human_attribute(object: object, attribute: key, locale: locale)
          next unless translate
          type = klass.columns_hash[key].type
          info.merge!({key => {value: value, locale_key: translate, type: type}})
        end
        
        info
      end 

      private
        # 返回false存在异意 仅供内部使用
        def human_attribute(object:, attribute:, locale: :zh)
          translate = object.class.human_attribute_name(attribute)
          # case locale.to_sym
          # when :zh, :zh_cn, :zh_CN
          #   return false unless (translate =~/^[\u4e00-\u9fa5]{1,}$/)
          # end
          translate
        end

    end
  end
end

radar/app/models/radar/business_logic/unite.rb
module Radar
  module BusinessLogic
    class Unite

      attr_reader :klass
      attr_reader :object
      attr_reader :zh_cn
      attr_reader :unite_id
      
      def initialize(object:)
        @klass = object.class.to_s
        @object = object
        @unite_id = "#{@klass}_#{object.id}"
        @zh_cn = nil
        load_attributes_zh_cn
        
        object.attributes.each do |column, value|
          define_singleton_method column.to_sym do
            value
          end
        end 
      end

      def new_record?
        !(id.present? rescue false)
      end 

      def klass_columns
        Unite.columns_info(klass: @klass)
      end 

      def self.columns_info(klass:)
        klass = klass.constantize if klass.is_a?(String)

        tmp = {}
        klass.columns.each do |column|
          human_read_name = klass.human_attribute_name(column.name)
          tmp.merge!({column.name => {locale_key: human_read_name, type: column.type, limit: column.limit, null: column.null, default: column.default}})
        end

        JSON.parse(tmp.to_json, object_class: OpenStruct)
      end

      private
        def load_attributes_zh_cn
          @zh_cn = Translation::human_attributes(object: @object)
        end 

        def load_attribute_infos
          @attributes_info = Translation::attributes_info(object: @object)
        end 
    end
  end
end

radar/app/models/radar/table_condition.rb
module Radar
  class TableCondition < ApplicationRecord
    serialize :search, Hash
    serialize :ransack, Hash
    serialize :show_columns, Array

    validates :table_name, :name, :search, :ransack, :is_default, presence: true
  end
end

radar/app/controllers/radar/application_controller.rb
module Radar
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def page_result(result)
      page_res = lambda{|result| result.page(params[:page_number] || 1).per(params[:page_size] || 100)}.call(result)
      (@max_page_number = page_res.total_pages) if init_load?
      (@result_size = result.size) if init_load?
      page_res
    end

    def init_load?
      init_load = params[:init_load]
      return true unless init_load
      init_load.downcase == 'true'
    end

    def auto_load?
      auto_load = params[:auto_load]
      return false unless auto_load
      auto_load.downcase == 'true'
    end

    def render(*args)
      if auto_load?
        super "shared/radar/_load_item", layout: false
      else
        super
      end 
    end

  end
end

radar/app/controllers/radar/manages_controller.rb
module Radar
  class ManagesController < ApplicationController
    before_action :initialize_instance_variable
    def index
      @klasses = BusinessLogic::Translation::human_object_names
    end

    def search_form
      render layout: false
    end

    def data_list
      if @show_columns.present?
        select_columns = @show_columns.map{|column| "#{@klass.table_name}.#{column}"}.uniq.join(', ')
        query = @klass.select(select_columns).ransack(handle_ransack)
      else
        query = @klass.ransack(handle_ransack)
      end
      datas = page_result(query.result)

      @unites = []
      datas.each do |object|
        @unites << BusinessLogic::Unite.new(object: object)
      end
      render layout: false
    end

    def object
      @object ||= @klass.new
      @unite = BusinessLogic::Unite.new(object: @object)
    end

    def object_info
      return (render text: 'klass不能为空') unless params[:klass]
      return (render text: 'object_id不能为空') unless params[:object_id]
      @unite = BusinessLogic::Unite.new(object: @object)
      render layout: false
    end

    def object_edit
      object = @object || @klass.new
      @unite = BusinessLogic::Unite.new(object: object)
      render layout: false
    end

    def object_update
      @object ||= @klass.new
      attributes = params[@klass_name].permit!.to_hash
      attributes = attributes.transform_values do |value| 
        (JSON.parse(value.gsub("=>", ":").gsub(":nil,", ":null,")) rescue value)
      end
      msg = nil
      unless (@object.update(attributes) rescue (msg = $!;false))
        return render json: {success: false, message: (msg || @error_messages.call(@object)).to_s}
      end
      render json: {success: true, message: '保存成功', object_id: @object.reload.id}
    end

    def save_condition
      condition = TableCondition.new(table_name: @klass.table_name, name: params[:condition_name])
      condition.search = @search
      condition.ransack = @ransack
      condition.show_columns = @show_columns

      unless condition.valid?
        return render json: {success: false, message: @error_messages.call(condition)}
      end

      unless condition.save
        return render json: {success: false, message: @error_messages.call(condition)}
      end

      render json: {success: true, message: '保存成功', condition_id: condition.id}
    end

    def object_delete
      return render json: {success: false, message: '对象为空'} unless @object.present?
      unless (@object.delete rescue (msg = $!;false))
        return render json: {success: false, message: ((msg ||= nil) || @error_messages.call(@object)).to_s}
      end
      render json: {success: true, message: '删除成功'}
    end

    def download
      if @show_columns.present?
        select_columns = @show_columns.map{|column| "#{@klass.table_name}.#{column}"}.uniq.join(', ')
        query = @klass.select(select_columns).ransack(handle_ransack)
      else
        query = @klass.ransack(handle_ransack)
      end
      datas = page_result(query.result)

      tmp = []
      query.result.each do |result|
        unite = BusinessLogic::Unite.new(object: result)
        tmp << unite.zh_cn
      end

      params = {
        api_code: :file_excel_create, 
        file_name: '虚构人物数据导出',
        sheets: [{name: '虚构人物数据导出', key_values: tmp}]
      }

      # res = Wireway::Spark.black_box(params)
      params.merge!(platform: 'black_box')
      res = Wireway::BusinessLogic::Restful.wireway(params)
      return (render json: {success: false, message: ('接口请求失败')}) unless res[0]

      params = {
        api_code: :file_download_send_file,
        rsa_pub: res[1][:rsa_pub]
      }

      begin
        res = RestClient.post "192.168.8.133:3116/black_box/restful/request_api", params
        unless res.code == 200
          return render json: {success: false, message: '文件处理组件请求失败'}
        end
        file_content = Base64.encode64(res.body)#.force_encoding('utf-8')

        return render json: {
          success: true,
          download: {
            mimetype: "application/excel",
            filename: "导出数据.xls",
            data: file_content,
          }
        }

      rescue => exception
        return render json: {success: false, message: '文件处理组件请求异常'}
      end

      render json: {success: false, message: '未知流程'}
    end

    private

      def handle_ransack
        return {} unless @search && @ransack
        tmp = {}
        @search.each do |key, value|
          tmp.merge!({"#{key}_#{@ransack[key]}" => (JSON.parse((value)) rescue value)})
        end
        tmp
      end 

      def initialize_instance_variable
        @error_messages = lambda do |object| 
          object.errors.messages.to_a.map do |key, value| 
            "#{@klass.human_attribute_name(key)}: #{value.join(', ')}"
          end.join(', ')
        end

        if params[:klass]
          klass = params[:klass].gsub('•', '::')
          @klass = (klass.constantize rescue nil)
          return (render text: 'class不存在') unless @klass
          @klass_name = klass.to_s.gsub('::', '•')
        end

        @search = params[:search] && params[:search].permit!.to_hash
        @ransack = params[:ransack] && params[:ransack].permit!.to_hash
        
        if params[:object_id].present? && @klass
          @object = @klass.find(params[:object_id])
          return (render text: 'object不存在') unless @object
        end

        table_condition_id = 1
        table_condition_id = params[:table_condition_id]
        @show_columns = (((params[:show_columns] || ActionController::Parameters.new).permit!.to_hash)[@klass.table_name] || []).delete_if{|item| !item.present? } if @klass

        @table_condictions = TableCondition.where(table_name: @klass.table_name) if @klass
        condiction = @table_condictions.find(table_condition_id) if table_condition_id && @table_condictions

        if condiction
          @search = condiction.search
          @ransack = condiction.ransack
          @show_columns = condiction.show_columns unless @show_columns.present?
        end

        @show_columns = (@klass.columns.map(&:name) - ['created_at', 'updated_at']) if @klass && @show_columns.blank?
      end 
      
  end
end

radar/app/helpers/radar/application_helper.rb
module Radar
  module ApplicationHelper

    def auto_load?
      auto_load = params[:auto_load]
      return false unless auto_load
      auto_load.downcase == 'true'
    end
    
    def auto_load(**args)
      render "shared/radar/auto_load", args
    end 

    def init_load?
      init_load = params[:init_load]
      return true unless init_load
      init_load.downcase == 'true'
    end

    def ransack_condictions
      {
        cont: '包含',
        eq: '等于',
        eq_any: '等于任意值',
        eq_all: '等于所有值',
        not_eq: '不等于',
        not_eq_any: '不等于任意值',
        not_eq_all: '不等于所有值',
        matches: '符合',
        matches_any: '符合任意条件',
        matches_all: '符合所有条件',
        does_not_match: '不符合',
        does_not_match_any: '符合任意条件',
        does_not_match_all: '不符合所有条件',
        lt: '小于',
        lt_any: '小于任意一个值',
        lt_all: '小于所有值',
        lteq: '小于等于',
        lteq_any: '小于等于任意一个值',
        lteq_all: '小于等于所有值',
        gt: '大于',
        gt_any: '大于任意一个值',
        gt_all: '大于所有值',
        gteq: '大于等于',
        gteq_any: '大于等于任意一个值',
        gteq_all: '大于等于所有值',
        in: '被包含',
        in_any: '被任意值包含',
        in_all: '被所有值包含',
        not_in: '不被包含',
        not_in_any: '不被任意值包含',
        not_in_all: '不被所有值包含',
        cont_any: '包含任意一个值',
        cont_all: '包含所有值',
        not_cont: '不包含',
        not_cont_any: '不包含任意一个值',
        not_cont_all: '不包含所有值',
        start: '以该值开始',
        start_any: '以任意一个值开始',
        start_all: '以所有值开始',
        not_start: '不以该值开始',
        not_start_any: '不以任意一个值开始',
        not_start_all: '不以所有值开始',
        end: '以该值结尾',
        end_any: '以任意一个值结尾',
        end_all: '以所有值结尾',
        not_end: '不以该值结尾',
        not_end_any: '不以任意一个值结尾',
        not_end_all: '不以所有值结尾',
        true: '等于true',
        false: '等于false',
        present: '有值',
        blank: '为空',
        null: '是null值',
        not_null: '不是null'
      }
    end
  end
end

radar/app/views/radar/manages/data_list.html.erb
<%
  columns_info ||= (@unites[0].zh_cn.keys rescue nil) || Radar::BusinessLogic::Unite::columns_info(klass: @klass).each_pair.to_a.map(&:last).map(&:locale_key)
%>

<div id="<%= @klass_name %>DataList" class='dataList'>
  <table class="table table-bordered table-striped table-hover" id="<%= @klass_name %>DataListTable">
    <thead>
      <tr>
        <td colspan="<%= columns_info.size+2 %>" class='text-center'>
          <button type="button" class="btn btn-primary disabled">
            总条数
            <span class="badge badge-light"><%= @result_size %></span>
          </button>
        </td>
      </tr>
      <tr>
        <th class="text-center" width='10%'>序号</th>
          <% columns_info.each do |column_name|%>
            <th class="text-center"><%= column_name %></th>
          <% end %>
        <th class="text-center">操作</th>
      </tr>
    </thead>
    <tbody>
      <%= render 'shared/radar/load_item' if @unites.present?%>
      <% unless @unites.present? %>
        <tr>
          <td colspan="<%= columns_info.size+2 %>" class='text-center'>
            无符合条件记录
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= auto_load(table_id: "#{@klass_name}DataListTable") %>

radar/app/views/radar/manages/index.html.erb
<% bg_colors = ['btn-primary','btn-success','btn-info','btn-warning','btn-danger','btn-secondary','btn-dark','btn-light'] %>

<style>
 label > input[type="checkbox"] {
    display: none;
  }

  label > input[type="checkbox"]:checked + *::before {
    content: "✓ ";
    color: white;
    text-align: center;
    /* background: white;
    border-color: white; */
  }
  label > input[type="checkbox"]:checked + * {
    color: white;
  }
</style>

<div class="jumbotron">
  <h1>数据列表</h1>
  <p>根据选择的对象,查询对象现有具体数据信息.</p>
  <div id="klass">
    <div id="klass_buttons">
      <% @klasses.each do |show_name, klass_name| %>
        <button type="button" class="btn mb-2 <%= bg_colors.sample %>" onclick="manage.changeKlass('<%= klass_name %>')"><%= show_name %></button>
      <% end %>
    </div>
    <div id="klass_options">
      <div class="input-group mb-3">
        <select id="klassSelect" onchange="manage.changeKlass()" class="form-control">
          <option value=''>请选择查询对象</option>
          <% @klasses.each do |show_name, klass_name| %>
            <option value="<%= klass_name %>"><%= show_name %>--<%= klass_name%></option>
          <% end %>
        </select>
      </div>
    </div>
  </div>
</div>

<div id="search">
  <div id="searchForms"></div>
</div>
<div id="data">
  <div id="dataLists"></div>
</div>

<script type="text/javascript">
  manage = new Object()
  manage.search = Object.create(manage)
  manage.datas = Object.create(manage)
  manage.data = Object.create(manage.datas)
  manage.info = Object.create(manage.data)
  
  // 获取当前查询的class
  manage.klass = function (){
    value = $("#klassSelect option:selected").val()
    return value
  }

  // 判断当前class是否为空
  manage.isKlassNull = function (){
    flag = (this.klass().length == 0)
    return flag
  }

  // 切换当前class
  manage.changeKlass = function (newKlass) {
    if(newKlass) $('#klassSelect').val(newKlass)

    if (this.isKlassNull()){
      $("div[class*='searchForm']").each(function(){
        $(this).addClass('d-none')
      })
      $("div[class*='dataList']").each(function(){
        $(this).addClass('d-none')
      })
      return
    }

    this.search.load()
    this.data.load()
  }


  // ============================ 搜索相关 ============================

  // 当前class对应的查询表单所属div
  manage.search.searchDiv = function () {
    return $('#'+this.klass()+'Search')
  }

  // 当前class对应的查询表单
  manage.search.searchForm = function () {
    return $('#'+this.klass()+'SearchForm')
  }

  // 加载当前class对应的查询表单
  manage.search.load = function (params) {
    params ||= {}
    if (this.isKlassNull()) return
    $("div[class='searchForm']").each(function(){ $(this).addClass('d-none')})
    
    if (this.searchDiv()[0]){
      this.searchDiv().removeClass('d-none')
      return
    }

    url = "<%= search_form_manages_path() %>"
    params = {klass: this.klass(), table_condition_id: params['tableConditionId']}
    space.network.ajax({"url": url, "params" : params}, function (result) {
      if (result[0]) $('#searchForms').append(result[1])
    })
  }

  // 重新当前clas的加载查询表单
  manage.search.reload = function (params) {
    params ||= {}
    this.searchDiv().remove()
    this.load(params)
  }

  // 根据所选条件名称加载
  manage.search.loadCondition = function (tableConditionId) {
    if (!tableConditionId) return
    this.searchDiv().remove()
    params = {"tableConditionId" : tableConditionId}
    this.load(params)
    this.datas.reload()
  }

  // 将当前搜索内容进行保存
  manage.search.saveCondition = function () {
    conditionName = prompt("输入条件名称", '')
    if (conditionName == null || conditionName == "") return space.page.alert('条件名称不能为空.')
    url = "<%= save_condition_manages_path() %>"+'?klass='+this.klass()+'&condition_name='+conditionName
    params = this.searchForm().serialize()
    space.network.ajax({type: 'Post', "url": url, "params" : params}, function (result) {
      if (!result[0]) return
      if (!result[1].success) return
      manage.search.reload({"tableConditionId" : result[1].condition_id})
    })
  }

  // 重置搜索内容
  manage.search.reset = function () {
    searchForm = $('#'+this.klass()+'SearchForm')
    searchForm[0].reset()
  }

  // ============================ 数据集合相关 ============================

  // 加载当前查询表单对应数据清单
  manage.datas.load = async function () {
    if (this.isKlassNull()) return
    $("div[class*='dataList']").each(function(){
      $(this).addClass('d-none')
    })
    
    dataList = $('#'+this.klass()+'DataList')
    if (dataList[0]){
      dataList.removeClass('d-none')
      return
    }

    if (!$('.searchForm')[0]) {
      for (let i = 0; i < 100; i++) {
        await sleep(1)
        if ($('.searchForm')[0]) i=100;
      }
    }

    form_data = $('#'+this.klass()+'SearchForm').serialize()
    url = "<%= data_list_manages_path() %>?klass="+this.klass()
    space.network.ajax({"url": url, "params" : form_data}, function (result) {
      if (result[0]) $('#dataLists').append(result[1])
    })
  }

  // 根据当前查询表单重新加载数据清单
  manage.datas.reload = function () {
    dataList = $('#'+this.klass()+'DataList')
    dataList.remove()
    this.data.load()
  }

  // 下载当前查询结果
  manage.datas.download = function () {
    if (this.isKlassNull()) return
    form_data = $('#'+this.klass()+'SearchForm').serialize()
    url = "<%= download_manages_path() %>?klass="+this.klass()
    space.network.ajax({"url": url, "params" : form_data}, function (result) {
      if (!result[0]) return space.page.alert(result[1].message || '接口调用失败')
      if (!result[1].success) return space.page.alert(result[1].message || '接口调用失败')
      res = space.data.downloadFile({fileName: '查询数据导出.xls', base64: result[1].download.data, mimetype: result[1].download.mimetype})
      if (!res[0]) return space.page.alert(res[1]);
    })
  }

  function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms))
  }

</script>

radar/app/views/radar/manages/object.html.erb
<div class="jumbotron">
  <h1>数据管理</h1>
  <div>
    <% unless @unite.new_record? %>
      <button class='btn btn-primary' type='button' onclick="object.info.load()">详细信息</button>
      <button class='btn btn-primary' type='button' onclick="object.edit.load()">编辑修改</button>
      <button class='btn btn-primary' type='button' onclick="space.page.alert('TODO: 尚未实现')">软删除</button>
      <button class='btn btn-primary' type='button' onclick="object.delete()">删除数据</button>
    <% else %>

    <% end %>
    <button class='btn btn-primary' type='button' onclick="location.href='<%= manages_path() %>'">返回列表</button>
  </div>
</div>
<div id="object">
  <div id="objectInfo"></div>
  <div id="objectEdit"></div>
</div>



<script type="text/javascript">
  var object = $("#object")
  
  object.klass = "<%= @klass_name %>"
  object.id = "<%= @unite.id %>"
  object.clean = function () {
    $("#object> div").each(function(){
      $(this).addClass('d-none')
    })
  }
  object.display = function (this_) {
    this.clean()
    this_.removeClass('d-none')
  }

  // ======================基础操作======================
  // 对象详情
  object.info = $("#objectInfo")
  object.info.load = function () {
    object.display(this)
    if (this.children()[0]) return

    url = "<%= object_info_manages_path() %>"
    params = {klass: object.klass, object_id: object.id}
    space.network.ajax({"url": url, "params" : params}, function (result) {
      if (result[0]) object.info.append(result[1])
    })
  }
  object.info.reload = function () {
    this.children().remove()
    this.load()
  }
  // 新建/修改对象
  object.edit = $("#objectEdit")
  object.edit.load = function () {
    object.display(this)
    this.children().remove()
    params = {klass: object.klass, object_id: object.id}
    url = "<%= object_edit_manages_path() %>"
    space.network.ajax({"url": url, "params" : params}, function (result) {
      if (result[0]) object.edit.append(result[1])
    })
  }
  object.edit.submit = function () {
    formData = this.children('form').serialize()
    url = "<%= object_update_manages_path() %>"

    space.network.ajax({type: 'Post',url: url, params: formData}, function (result) {
      if (!result[0]) return

      res= result[1]
      if (!res.success) return space.page.alert(res.message || '数据保存失败')
      if ((object.id.length > 0) && (object.id == res.object_id)) return object.info.reload()

      url = "<%= object_manages_path() %>"
      url += '?klass='+object.klass+'&object_id='+res.object_id
      window.location.replace(url)
    })
  }
  // 删除对象
  object.delete = function () {
    url = "<%= object_delete_manages_path() %>"
    params = {klass: object.klass, object_id: object.id}
    space.network.ajax({"url": url, "params" : params}, function (result) {
      if (!result[0]) return
      if (!result[1].success) return space.page.alert(result[1].message)
      window.location.replace("<%= manages_path() %>")
    })
  }
  // ======================对象分析======================
  // 属性分析
  if (object.id.length > 0) {
    object.info.load()
  }else{
    object.edit.load()
  }
</script>

radar/app/views/radar/manages/object_edit.html.erb
<% 
  base_params = []
  split_size ||= 2 
  lable_style ||= "width: #{((100 / split_size)*(3/10.to_f)).to_i}%;"
  content_style ||= "width: #{((100 / split_size)*(7/10.to_f)).to_i}%;"
  columns = @unite.klass_columns.each_pair.to_a
%>

<div class="pb-3">
  <button class='btn btn-primary' type='button' onclick="object.edit.submit()">提交</button>
  <input class='btn btn-primary' type='submit' form="_attributesForm" formaction="" value="强制提交" onclick="space.page.alert('TODO: 尚未实现');">
</div>

<form method='post' id="editForm">
  <%= tag(:input, :type => "hidden", name: request_forgery_protection_token.to_s, value: form_authenticity_token) %>
  <input type="hidden" name="klass" value="<%= @klass_name %>">
  <input type="hidden" name="object_id" value="<%= @unite.id %>">

  <table class="table table-bordered table-striped table-hover">
    <tbody>
      <% columns.to_a.in_groups_of(split_size, 'none').each do |array| %>
        <tr>
          <% array.each do |column, info| %>
            <% if column == 'none' %>
              <td style="<%= lable_style %>"></td>
              <td style="<%= content_style %>"></td> 
              <% next %>
            <% end %>
            
            <td style="<%= lable_style %>" class="text-right"><%= info.locale_key %></td>
            <td style="<%= content_style %>">
              <input class='w-100' name="<%= @klass_name %>[<%= column %>]" value="<%= @unite.send(column) %>"/>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</form>

radar/app/views/radar/manages/object_info.html.erb
<%= render 'shared/radar/kv_table_y', base_params: @unite.zh_cn %>

radar/app/views/radar/manages/search_form.html.erb
<style>
  table input {
    width: 100%;
    height: 36px;
  }
</style>

<%
  columns_infos ||= Radar::BusinessLogic::Unite::columns_info(klass: @klass).each_pair.to_a
  split_size ||= 2 
  lable_style ||= "width: #{((100 / split_size)*(3/10.to_f)).to_i}%;"
  content_style ||= "width: #{((100 / split_size)*(7/10.to_f)).to_i}%;"
%>

<div id="<%= @klass_name %>Search" class='searchForm'>
  <form method='get' id="<%= @klass_name %>SearchForm">
    <%= tag(:input, :type => "hidden", name: request_forgery_protection_token.to_s, value: form_authenticity_token) %>
    <table class='table table-bordered table-striped table-hover'>
      <% columns_infos.in_groups_of(split_size, 'none').each do |array| %>
        <tr>
          <% array.each do |column_name, info|%>
            <% if column_name == 'none' %>
              <td style="<%= lable_style %>"></td>
              <td style="<%= content_style %>"></td> 
              <% next %>
            <% end %>
            <td class='text-right' style="<%= lable_style %>">
              <span class="float-right"><%= info.locale_key %></span>
            </td>
            <td style="<%= content_style %>">
              <% search_value = (@search||{}).select{|k,v| k.to_sym == column_name}.values[0] %>
              <% ransack_value = (@ransack||{}).select{|k,v| k.to_sym == column_name}.values[0] %>
              <div width='100%'>
                <select class="form-control w-25 float-left" name="ransack[<%= column_name%>]">
                  <% ransack_condictions.each do |key, value| %>
                    <% if ransack_value && (key == ransack_value.to_sym)%>
                      <% add = 'SELECTED' %>
                    <% elsif (info.type == 'integer') && (key == :eq) %>
                      <% add = 'SELECTED' %>
                    <% end %>
                    <option value="<%= key %>" <%= add ||= nil %>><%= value %></option>
                  <% end %>
                </select>
                <input class='w-75 float-left' name="search[<%= column_name %>]" value="<%= search_value %>"/>
              </div>
            </td>
          <% end %>
        </tr>
      <% end %>

      <tr>
        <td colspan="<%= split_size*2 %>" class='text-center'>
          <%# <div class="btn-group btn-group-toggle" data-toggle="buttons"> %>
            <% columns_infos.each do |name, info|%>
                <label class="btn btn-primary">
                  <% add = (@show_columns.include?(name.to_s) ? 'checked' : nil) %>
                  <input type="checkbox" name="show_columns[<%= @klass.table_name %>][]" value="<%= name %>" autocomplete="off" <%= add %>><span><%= info.locale_key %></span>
                </label>
            <% end %>
          <%# </div> %>
        </td>
      </tr>

      <% if @table_condictions.present? %>
        <tr>
          <td colspan="<%= split_size*2 %>" class='text-center'>
            <% @table_condictions.each do |table_condiction|%>
              <button class='btn btn-primary' type='button' onclick="manage.search.loadCondition('<%= table_condiction.id %>');"><%= table_condiction.name %></button>
            <% end %>
          </td>
        </tr>
      <% end %>

      <tr>
        <td colspan="<%= split_size*2 %>" class='text-center'>
          <button class='btn btn-primary' type='button' onclick="manage.search.saveCondition();">保存条件</button>
          <button class='btn btn-primary' type='button' onclick="location.href='<%= object_manages_path(klass: @klass_name) %>'">新增记录</button>          
          <button class='btn btn-primary' type='button' onclick="manage.search.reset();">重置条件</button>
          <button class='btn btn-primary' type='button' onclick="manage.search.reload();">清空条件</button>
          <button class='btn btn-primary' type='button' onclick="manage.datas.download();">导出结果</button>
          <button class='btn btn-primary' type='button' onclick="manage.search.reload();manage.datas.reload();">全部结果</button>
          <button class='btn btn-primary' type='button' onclick="manage.datas.reload();">查询结果</button>
        </td>
      </tr>
    </table>
  </form>
</div>